version: "3.9"

services:
  auth_service:
    build: ./auth_service
    container_name: auth_service
    volumes:
      - ./auth_service:/app
    ports:
      - "8000:8000"
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
